### ISSUE TITLE
Page request: testimonials & advice

### ISSUE THREAD

**Issue by ngjunsiang** [nyjc-computing/nyjc-computing.github.io#6]
Add a page containing testimonials & advice from past cohorts of seniors.

## Task

1. Add testimonials and advice from seniors in a new page.
   - You can get initial content from the shared google drive (look under Miscellaneous folder).
   - I will add more content from this year's J2s once it is available; I will follow the existing format that is laid down.
2. Create an appropriate layout for the content, including new page template, if necessary.

## Deliverables

- [x] Testimonials and advice from seniors appears in a new page, appropriately organized
- [x] The page is written in Markdown for easy editing
- [x] The page layout has room for adding of testimonials and advice from future cohorts

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Create a new page for testimonials and advice from seniors, and add a link to it in the navigation.

You can review changes in this commit: https://github.com/mnmnk43434/nyjc-computing-nyjc-computing.github.io-6/commit/2ce767e5386be9b4cbb8ccb5b7dfafe1545fc2ba.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by its-kenneth** [comment]
Page created with initial content from Google Drive.

**Comment by ngjunsiang** [comment]
@its-kenneth in future create a new branch for any issue before working on code :) There is a shortcut in the right sidebar you can use - "Create a branch" under Development:

![image](https://github.com/user-attachments/assets/99fd1c52-5044-471f-b298-22812d2a0959)

Work in that branch, then make a pull request to `content` branch when ready.

**Comment by ngjunsiang** [comment]
Without the commits in a new branch, it's difficult for me to comment on changes (because your branch commits don't appear in a PR).

I will close the issue when it's done.

**Comment by ngjunsiang** [comment]
From https://github.com/nyjc-computing/nyjc-computing.github.io/commit/29a3eb567c2402e98d69d958d06b182fc459f654 it looks like the testimonials are written in HTML. This actually makes future edits harder, because if the site layout changes the page HTML will have to change as well.

For now, keep the content in Markdown -- see the `.md` pages for an example, or ping me if this is unclear. It looks like testimonial page will need a separate template for a 2-column layout, I'll create a separate issue for that.

**Comment by its-kenneth** [comment]
@ngjunsiang hi Mr Ng, I’ve created the pull request to content.
